version: "3.7"

services:

#  user-service:
#    build:
#      context: .
#      args:
#        SERVICE: user
#    command: [ "/bin/user" ]
#    ports:
#      - "8086:8086"
#    depends_on:
#      - user-database
#
#  order-service:
#    build:
#      context: .
#      args:
#        SERVICE: order
#    command: [ "/bin/order" ]
#    ports:
#      - "1323:1323"
#    depends_on:
#      - order-database
#
#  product-service:
#    build:
#      context: .
#      args:
#        SERVICE: product
#    command: [ "/bin/product" ]
#    ports:
#      - "8087:8087"
#    depends_on:
#      - product-database

  product-database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    container_name: product-database
    volumes:
      - productDB:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Roo7t0lk2o20
      MYSQL_DATABASE: product_db
      MYSQL_USER: hellofresh
      MYSQL_PASSWORD: productPassword

  user-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: user-database
    volumes:
      - userDB:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Roo7t0lk2o20
      MYSQL_DATABASE: user_db
      MYSQL_USER: hellofresh
      MYSQL_PASSWORD: userPassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  order-database:
    image: mysql:8.0
    ports:
      - "3309:3306"
    container_name: order-database
    volumes:
      - orderDB:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Roo7t0lk2o20
      MYSQL_DATABASE: order_db
      MYSQL_USER: hellofresh
      MYSQL_PASSWORD: orderPassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hellofresh
      - RABBITMQ_DEFAULT_PASS=food
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  productDB:
  userDB:
  orderDB: